### ISSUE TITLE
1레벨 페어 피드백

### ISSUE THREAD

**Issue by ironprayer** [2kyuhang/memotest#1]
단건 조회는 id를 Pathvariable로 받으셨는데, 수정 삭제에서는 id를 RequestBody에 담아서 받으신 이유가 있으실까요? id의 경우 Pathvariable로 받는 것이 더 적합해보여서요

**Comment by 2kyuhang** [comment]
> 단건 조회는 id를 Pathvariable로 받으셨는데, 수정 삭제에서는 id를 RequestBody에 담아서 받으신 이유가 있으실까요? id의 경우 Pathvariable로 받는 것이 더 적합해보여서요

한번에 받으려 하다보니 묶어야겠다는 생각을 했었는데 id(Pathvariable)와 분리해 memo(RequestBody)으로 변경하겠습니다.

**Comment by ironprayer** [comment]
Dto가 4개나 만들어져 있던데, DeletRequestDto, UpdateRequestDto, RequestDto는 중복이 되는 것 같아요. 혹시 이렇게 나눠서 작성하신 이유가 있으실까요? 없으시면 하나로 합쳐서 진행해보는 건 어떨까요?

**Comment by 2kyuhang** [comment]
> Dto가 4개나 만들어져 있던데, DeletRequestDto, UpdateRequestDto, RequestDto는 중복이 되는 것 같아요. 혹시 이렇게 나눠서 작성하신 이유가 있으실까요? 없으시면 하나로 합쳐서 진행해보는 건 어떨까요?

memo객체로만 주고 받으면 null값이 생길거 같아 새로운 request객체를 만들었습니다.

**Comment by ironprayer** [comment]
그러시군요. 하나의 클래스로 사용하다보면 null 값으로 들어오는 값들이 생기겠군요. 그 부분은 미처 생각하지 못했네요.

**Comment by ironprayer** [comment]
그래도 참고용으로 dto 쪽에 null값을 체크해주는 어노테이션이 존재해요. @Notnull 이런건데 이런 것 사용해보시면 null에 대한 걱정을 더실 수 있을 것 같습니다.

**Comment by ironprayer** [comment]
Service쪽에 JPA dirty Checking을 사용하시는 것 같은데, 왜 따로 save를 사용하셨나요? 중복이 되는 것 같습니다. 지워도 동작을 할 것 같아요.

**Comment by 2kyuhang** [comment]
> Service쪽에 JPA dirty Checking을 사용하시는 것 같은데, 왜 따로 save를 사용하셨나요? 중복이 되는 것 같습니다. 지워도 동작을 할 것 같아요.

그 부분은 JPA의 내용을 완전히 이해 못해 강의 내용과 똑같이 하려고 하다보니 중복된코드가 나왔습니다.

**Comment by ironprayer** [comment]
deleteMemo에 exception 선언만 하고 던지지 않았는데 이유가 있으실까요? 예외 생성만으로는 처리가 되지 않습니다. 그리고 바로 아래 return이 있던데 예외가 던져지게 되면 return이 동작하지 않습니다. 둘 중 하나만 사용해보시는 건 어떨까요?

**Comment by 2kyuhang** [comment]
> deleteMemo에 exception 선언만 하고 던지지 않았는데 이유가 있으실까요? 예외 생성만으로는 처리가 되지 않습니다. 그리고 바로 아래 return이 있던데 예외가 던져지게 되면 return이 동작하지 않습니다. 둘 중 하나만 사용해보시는 건 어떨까요?

오류 생성 코드를 잘 몰랐었고 알려주신 내용 확인했습니다!

**Comment by ironprayer** [comment]
Repository에 사용되지 않는 쿼리메서드들이 많던데, 사용하지 않는 경우 삭제를 하면 헷갈릴 여지가 없을 것 같습니다. 혹시 추후에 사용하시려고 남겨두시는 걸까요?

**Comment by 2kyuhang** [comment]
과제를 급하게 제출하려다보니 복붙과정에서 확인하지 못했습니다.
수정하겠습니다.

**Comment by ironprayer** [comment]
네네 알겠습니다. 제가 확인한 코드는 여기까지입니다. 수고하셨습니다.

**Comment by 2kyuhang** [comment]
> 네네 알겠습니다. 제가 확인한 코드는 여기까지입니다. 수고하셨습니다.

수고하셨습니다!!!
